### ISSUE TITLE
Make database pool size configurable

### ISSUE THREAD

**Issue by hughjfchen** [portnov/batchd#38]
## Problem statement
Currently, the database pool size looks like fixed to 10 in the dispatcher. Would like to make it configurable in the batchd.yml file.

## Steps to reproduce

1. Take a look at the Dispatcher.hs
2.
3.

## Expected result
Add a parameter in batchd.yml to config the db pool.

## Actual result
The pool size fixed to 10 within the Dispatcher.hs

## batchd version
Github Master

Please specify whether you are using installation from hackage, or building source from github.
I built from github master.

**Comment by portnov** [comment]
done.
