### ISSUE TITLE
Minor error in the wiki page Host_management

### ISSUE THREAD

**Issue by hughjfchen** [portnov/batchd#39]
## Problem statement
The wiki page Host_management has following:
`Example config (~/.config/batchd/controllers/aws1.yaml):`
The `controllers` within the path should be `hosts`
## Steps to reproduce

1. browse the wiki Host_management page
2.
3.

## Expected result
Example config (~/.config/batchd/hosts/aws1.yaml):

## Actual result
Example config (~/.config/batchd/controllers/aws1.yaml):

## batchd version
Github master

Please specify whether you are using installation from hackage, or building source from github.
Built from github

**Comment by portnov** [comment]
fixed
