### ISSUE TITLE
No log output

### ISSUE THREAD

**Issue by hughjfchen** [portnov/batchd#43]
## Problem statement
There is no log output no matter which log level I set.

## Steps to reproduce
1.make sure set the log level to config in batchd.yaml
2.start batchd as manager/dispatcher
3.no log output

## Expected result
There should be some log output which indicating what were happenning.

## Actual result
No log outout.

## batchd version
Github master.

Please specify whether you are using installation from hackage, or building source from github.
Built from github master.

**Comment by hughjfchen** [comment]
Or should I raise the issue to the upstream packages, heavy-logger?

**Comment by hughjfchen** [comment]
After having gone through the source, I found that there is a log Target in the config file, and the default target is syslog. After add a `target: stdout` within the config file `batchd.yaml`, I got log message.

**Comment by portnov** [comment]
I think this can be marked as resolved.
