### ISSUE TITLE
batchd-admin create-superuser failed

### ISSUE THREAD

**Issue by hughjfchen** [portnov/batchd#44]
## Problem statement
batchd-admin create-superuser failed with the following error message:
batchd-admin: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
  undefined, called at ./Text/Localize/IO.hs:31:50 in localize-0.2.0.0-E2uKI53Vt4bH64hm5CJQAO:Text.Localize.IO

## Steps to reproduce
1. run batchd-admin create-superuser
2. got the above error message
3.

## Expected result
Create the super user in the database

## Actual result
Got error message as above.

## batchd version
Github master

Please specify whether you are using installation from hackage, or building source from github.
Built with github master

**Comment by hughjfchen** [comment]
Having gone through the source, I guess that maybe due to lack of some PO/MO files? If yes, I think a deployment guide should be put into wiki to clarify the requirements.

**Comment by hughjfchen** [comment]
OK. Gone through the source and found the `getPassword2` using `Localize` package for localized message and will crash maybe due to lack of PO/MO files, I fixed it with the following quick and dirty hack:
Changed `getPassword =<< (__s "Password: " )` to `getPassword "Password: "`

**Comment by portnov** [comment]
Should be fixed in master.
