### ISSUE TITLE
Optional fields within Host config file always parsed as Nothing

### ISSUE THREAD

**Issue by hughjfchen** [portnov/batchd#45]
## Problem statement
Optional fields within a Host configuration file always pared as Nothing.

## Steps to reproduce
1. make a host config file with some optional fields
2.submit a job to run on this host
3.from the log, the optional fields always Nothing even it's presented 

## Expected result
The fields should use the values within the Host config file

## Actual result
Always set Nothing.

## batchd version
Github master

Please specify whether you are using installation from hackage, or building source from github.
Built with the github master

**Comment by portnov** [comment]
Can't reproduce :/
If you have an example of config which loads incorrectly, feel free to reopen.
